# Site settings
title: Copenhagen Ruby Brigade
description: >
  A group of Ruby enthusiasts from Copenhagen, Denmark who meet roughly every
  third month to talk about Ruby, programming, and other related topics.
baseurl: ""
url: "http://copenhagenrb.dk"
twitter_username: copenhagenrb
github_username: copenhagenrb

# Build settings
markdown: kramdown

exclude:
  - README.md

# Site variables
companies:
  - name: Abtion
    url: http://www.abtion.com
  - name: Autobutler
    url: http://www.autobutler.dk
  - name: Be My Eyes
    url: http://www.bemyeyes.org/
  - name: BiQ
    url: http://www.biq.dk
  - name: Billetto
    url: https://billetto.dk
  - name: Capgemini
    url: http://www.capgemini.dk/
  - name: Donkey Republic
    url: https://www.donkey.bike/
  - name: Downtown
    url: http://www.downtown.dk
  - name: Driversnote
    url: https://www.driversnote.com
  - name: Fab:IT ApS
    url: http://fab-it.dk/
  - name: Firmafon
    url: http://www.firmafon.dk
  - name: GoMore
    url: http://www.gomore.dk
  - name: Greenline
    url: https://www.greenline.dk
  - name: Karnov
    url: http://www.karnov.dk
  - name: Lokalebasen
    url: http://www.lokalebasen.dk
  - name: myphoner
    url: https://www.myphoner.com
  - name: NineConsult
    url: http://www.nineconsult.dk
  - name: Nokia
    url: http://www.nokia.dk
  - name: Podio
    url: https://www.podio.com
  - name: Single.dk
    url: http://www.single.dk
  - name: Substance Lab
    url: http://substancelab.dk
  - name: Tonsser
    url: https://tonsser.com
  - name: Vivino
    url: http://www.vivino.com
  - name: Zendesk
    url: http://www.zendesk.com
  - name: Zetland
    url: https://www.zetland.dk
